name: CI

on: 
  repository_dispatch:
    types: dx-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      run: echo "$CLIENT_PAYLOAD"
