name: preview       
          
on:
  pull_request:
    types: [synchronize, opened, labeled, unlabeled, edited]
  

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webhook
        if: always()
        env: 
          CONTEXT: ${{ toJson(github) }} 
          JOB: "{ 'name': 'start', 'status': '${{ job.status }}', 'next': 'Install & Build' }"
        run: |
            chmod -R +x ./.github/scripts
            node ./.github/scripts/webhook.js
  build:
    name: Install & Build
    needs: [start]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump job context
      env:
       JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
          
    - name: NPM Install & Build
      run: |
          npm ci
          npm run ng build --prod dx-apd
      env:
        CI: true
  
    - name: Deploy App
      uses: w9jds/firebase-action@master
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
          args: deploy --only hosting:dx-lib-starter -m "${{ github.head_ref }}-pr-${{ github.event.pull_request.id }}"  
    
    - name: Webhook
      if: success()
      env:
        CONTEXT: ${{ toJson(github) }} 
        VERSION: 0.1.0
        JOB: "{ 'name': 'Install & Build', 'status': '${{ job.status }}' }" 
      run: |
         chmod -R +x ./.github/scripts
         node ./.github/scripts/webhook.js 
    - name: Webhook
      if: failure()
      env:
        CONTEXT: ${{ toJson(github) }} 
        JOB: "{ 'name': 'Install & Build', 'status': '${{ job.status }}' }" 
      run: |
         chmod -R +x ./.github/scripts
         node ./.github/scripts/webhook.js   

