name: CI
 
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: '{"step": "NPM Install & Build", "trigger": "pull_request", "repository": "${{ github.event.repository.name }}"}'
    - name: NPM Install & Build
      run: |
          npm ci
          npm run ng build --prod dx-app
      env:
        CI: true
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: '{"step": "Deploy App", "trigger": "pull_request", "repository": "${{ github.event.repository.name }}"}'
    - name: Deploy App
      uses: w9jds/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting:dx-lib-starter -m "${{ github.head_ref }}-pr-${{ github.event.pull_request.id }}"  
