name: CI

on: [pull_request]

env:
  SCRIPTS_PATH: ./.github/scripts # directory used for github actions scripts.

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        env: 
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'in progress'}], 'trigger': 'pull_request', 'repository': '${{ github.event.repository.name }}-head'}"
        run: |
            ${{ env.SCRIPTS_PATH }}/webhook.sh

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "{'steps':[{'name':'Set up project','status':'complete'},{'name':'Install and build','status':'in progress'}], 'trigger': 'pull_request', 'repository': '${{ github.event.repository.name }}-head'}"
    - name: NPM Install & Build
      run: |
          npm ci
          npm run ng build --prod dx-app
      env:
        CI: true
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "{'steps':[{'name':'Set up project','status':'complete'},{'name':'Install and build','status':'complete'}, { 'name': 'Deploy', 'status':'in progress' }], 'trigger': 'pull_request', 'repository': '${{ github.event.repository.name }}-head'}"
    - name: Deploy App
      uses: w9jds/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting:dx-lib-starter -m "${{ github.head_ref }}-pr-${{ github.event.pull_request.id }}"  
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "{'steps':[{'name':'Set up project','status':'complete'},{'name':'Install and build','status':'complete'}, { 'name': 'Deploy', 'status':'complete' }], 'trigger': 'pull_request', 'repository': '${{ github.event.repository.name }}-head'}"  
