name: Create release  
 
on:
  push:
    branches:
    - master

env:
  NODE_VERSION: "12.x"            # node version to use
  PACKAGES_PATH: $HOME/packages   # directory used to store user data in /home/runner/packages.
  SECRETS_PATH: $HOME/secrets     # directory used to store secrets in /home/runner/secrets.
  SCRIPTS_PATH: ./.github/scripts # directory used for github actions scripts.
  APP_NAME: dx-app             # application's name.
  APP_DIST: dist/dx-app/       # Application dist path.
  VERSION: "0.0.1"  

jobs:
  create-release:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'in progress'}], 'trigger': 'push', 'repository': '${{ github.event.repository.name }}-base'}"
      - name: Filesystem Config
        run: |
          #chmod -R +x ${{ env.SCRIPTS_PATH }}
          mkdir -p ${{ env.PACKAGES_PATH }}   
          mkdir -p ${{ env.SECRETS_PATH }}
      - uses: actions/checkout@master

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@distinctlab"   
           
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'complete'}, {'name':'Install and build','status':'in progress'}], 'trigger': 'push', 'repository': '${{ github.event.repository.name }}-base'}"         
      - name: Install - Build
        run: |
          npm ci
          npm run ng build --prod dx-app
        env:
          CI: true
          
          
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'complete'}, {'name':'Install and build','status':'complete'}, {'name':'Create release','status':'in progress'}], 'trigger': 'push', 'repository': '${{ github.event.repository.name }}-base'}"         
      - name: Package Artifacts
        run: |
          tar zcvf ${{ env.APP_NAME }}-${{ env.VERSION }}.tar.gz  ${{ env.APP_DIST }}



      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.APP_NAME }}-${{ env.VERSION }}.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
   
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'complete'}, {'name':'Install and build','status':'complete'}, {'name':'Create release','status':'complete'}, {'name':'Deploy','status':'in progress'}], 'trigger': 'push', 'repository': '${{ github.event.repository.name }}-base'}"         
      - name: Deploy App
        uses: w9jds/firebase-action@master
        env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
         args: deploy --only hosting:dx-lib-starter -m "${{ env.VERSION }}"    
       
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'steps':[{'name':'Set up project','status':'complete'}, {'name':'Install and build','status':'complete'}, {'name':'Create release','status':'complete'}, {'name':'Deploy','status':'complete'}], 'trigger': 'push', 'repository': '${{ github.event.repository.name }}-base'}"         
      
